export const STOCKS_INFORMATIONS_REQUEST = 'STOCKS_INFORMATIONS_REQUEST'
export const STOCKS_INFORMATIONS_SUCCESS = 'STOCKS_INFORMATIONS_SUCCESS'
export const STOCKS_INFORMATIONS_FAIL = 'STOCKS_INFORMATIONS_FAIL'