export const CANDLE_REQUEST = 'CANDLE_REQUEST'
export const CANDLE_SUCCESS = 'CANDLE_SUCCESS'
export const CANDLE_FAIL = 'CANDLE_FAIL'

export const INFO_REQUEST = 'INFO_REQUEST'
export const INFO_SUCCESS = 'INFO_SUCCESS'
export const INFO_FAIL = 'INFO_FAIL'

export const FAV_STOCKS_REQUEST = 'FAV_STOCKS_REQUEST'
export const FAV_STOCKS_SUCCESS = 'FAV_STOCKS_SUCCESS'
export const FAV_STOCKS_FAIL = 'FAV_STOCKS_FAIL'

export const FAV_STOCKS_UPDATE__REQUEST = 'FAV_STOCKS_UPDATE__REQUEST'
export const FAV_STOCKS_UPDATE__SUCCESS = 'FAV_STOCKS_UPDATE__SUCCESS'
export const FAV_STOCKS_UPDATE__FAIL = 'FAV_STOCKS_UPDATE_FAIL'