export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_VERIFIER_REQUEST = 'USER_VERIFIER_REQUEST'
export const USER_VERIFIER_SUCCESS = 'USER_VERIFIER_SUCCESS'
export const USER_VERIFIER_FAIL = 'USER_VERIFIER_FAIL'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'


export const CODE_REGISTER_REQUEST = 'CODE_REGISTER_REQUEST'
export const CODE_REGISTER_SUCCESS = 'CODE_REGISTER_SUCCESS'
export const CODE_REGISTER_FAIL = 'CODE_REGISTER_FAIL'